<?php

use App\Http\Controllers\Api\V1\AdminFixtureController;
use App\Http\Controllers\Api\V1\AdminMatchController;
use App\Http\Controllers\Api\V1\AdminPlayerController;
use App\Http\Controllers\Api\V1\AdminDraftController;
use App\Http\Controllers\Api\V1\AdminTeamController;
use App\Http\Controllers\Api\V1\AdminResultController;
use App\Http\Controllers\Api\V1\AdminTournamentController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\DraftController;
use App\Http\Controllers\Api\V1\MatchController;
use App\Http\Controllers\Api\V1\ProfileController;
use App\Http\Controllers\Api\V1\RegistrationController;
use App\Http\Controllers\Api\V1\ScoringController;
use App\Http\Controllers\Api\V1\SyncController;
use App\Http\Controllers\Api\V1\AdminStageController;
use App\Http\Controllers\Api\V1\SuperAdminController;
use App\Http\Controllers\Api\V1\TournamentController;
use App\Http\Controllers\Api\V1\SearchController;
use App\Http\Controllers\Api\V1\NewsController;
use App\Http\Controllers\Api\V1\OrganizationController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->middleware('throttle:api')->group(function () {
    Route::post('auth/register', [AuthController::class, 'register'])->middleware('throttle:api-auth')->name('api.v1.auth.register');
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:api-auth')->name('api.v1.auth.login');
    Route::get('tournaments', [TournamentController::class, 'index'])->name('api.v1.tournaments.index');
    Route::get('tournaments/{tournament}', [TournamentController::class, 'show'])->name('api.v1.tournaments.show');
    Route::get('tournaments/{tournament}/teams', [TournamentController::class, 'teams'])->name('api.v1.tournaments.teams');
    Route::get('tournaments/{tournament}/players', [TournamentController::class, 'players'])->name('api.v1.tournaments.players');
    Route::get('tournaments/{tournament}/players/compare', [TournamentController::class, 'compare'])->name('api.v1.tournaments.players.compare');
    Route::get('tournaments/{tournament}/fixtures', [TournamentController::class, 'fixtures'])->name('api.v1.tournaments.fixtures');
    Route::get('tournaments/{tournament}/standings', [TournamentController::class, 'standings'])->name('api.v1.tournaments.standings');
    Route::get('tournaments/{tournament}/standings/simulate', [TournamentController::class, 'simulateStandings'])->name('api.v1.tournaments.standings.simulate');
    Route::get('matches/{match}/state', [MatchController::class, 'state'])->name('api.v1.matches.state');
    Route::get('tournaments/{tournament}/sync', [SyncController::class, 'tournament'])->name('api.v1.tournaments.sync');
    Route::get('players/{playerProfile}', [ProfileController::class, 'showPlayer'])->name('api.v1.players.show');
        Route::get('players/{playerProfile}/stats', [ProfileController::class, 'stats'])->name('api.v1.players.stats');
        Route::get('players/{playerProfile}/insights', [ProfileController::class, 'insights'])->name('api.v1.players.insights');
        Route::get('players/{playerProfile}/matches', [ProfileController::class, 'matches'])->name('api.v1.players.matches');
        Route::get('players/{playerProfile}/teams', [ProfileController::class, 'teams'])->name('api.v1.players.teams');
    Route::get('teams/{team}/squad', [TournamentController::class, 'squad'])->name('api.v1.teams.squad');
    Route::post('teams/{team}/designations', [TournamentController::class, 'updateDesignations'])->middleware('auth:sanctum')->name('api.v1.teams.designations');
    Route::get('teams/compare', [TournamentController::class, 'compareTeams'])->name('api.v1.teams.compare');
    Route::get('search', [SearchController::class, 'search'])->name('api.v1.search');
    Route::get('search/lookup/{code}', [SearchController::class, 'lookup'])->name('api.v1.search.lookup');
    Route::get('news', [NewsController::class, 'index'])->name('api.v1.news.index');
    Route::get('news/{newsArticle}', [NewsController::class, 'show'])->name('api.v1.news.show');
    Route::get('organizations', [OrganizationController::class, 'index'])->name('api.v1.organizations.index');
    Route::get('organizations/{organization}', [OrganizationController::class, 'show'])->name('api.v1.organizations.show');

    Route::middleware('auth:sanctum')->group(function () {
        Route::get('auth/me', [AuthController::class, 'me'])->name('api.v1.auth.me');
        Route::post('auth/logout', [AuthController::class, 'logout'])->name('api.v1.auth.logout');
        Route::post('auth/logout-all', [AuthController::class, 'logoutAll'])->name('api.v1.auth.logout-all');
        Route::get('profile', [ProfileController::class, 'show'])->name('api.v1.profile.show');
        Route::match(['post', 'patch'], 'profile', [ProfileController::class, 'update'])->name('api.v1.profile.update');
        Route::get('tournaments/{tournament}/registration', [RegistrationController::class, 'mine'])->name('api.v1.tournaments.registration.mine');
        Route::post('tournaments/{tournament}/registration', [RegistrationController::class, 'store'])->middleware('throttle:20,1')->name('api.v1.tournaments.registration.store');
        Route::get('tournaments/{tournament}/draft/state', [DraftController::class, 'state'])->middleware(['role:captain', 'permission:make draft pick', 'draft.enabled'])->name('api.v1.tournaments.draft.state');
        Route::post('tournaments/{tournament}/draft/pick', [DraftController::class, 'pick'])->middleware(['role:captain', 'permission:make draft pick', 'draft.enabled'])->name('api.v1.tournaments.draft.pick');
        Route::post('matches/{match}/deliveries', [ScoringController::class, 'store'])->middleware(['permission:control draft', 'throttle:120,1'])->name('api.v1.matches.deliveries.store');
        Route::post('matches/{match}/deliveries/sync', [ScoringController::class, 'sync'])->middleware(['permission:control draft', 'throttle:120,1'])->name('api.v1.matches.deliveries.sync');
        Route::patch('deliveries/{matchDelivery}', [ScoringController::class, 'editDelivery'])->middleware(['permission:control draft', 'throttle:120,1'])->name('api.v1.deliveries.edit');
        Route::post('matches/{match}/next-innings', [ScoringController::class, 'nextInnings'])->middleware(['permission:control draft', 'throttle:30,1'])->name('api.v1.matches.next-innings');
        Route::post('matches/{match}/undo', [ScoringController::class, 'undo'])->middleware(['permission:control draft', 'throttle:30,1'])->name('api.v1.matches.undo');
        Route::get('matches/{match}/mvp', [ScoringController::class, 'mvp'])->name('api.v1.matches.mvp');
        Route::get('admin/tournaments', [AdminTournamentController::class, 'index'])->middleware('permission:manage tournaments')->name('api.v1.admin.tournaments.index');
        Route::post('admin/tournaments', [AdminTournamentController::class, 'store'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.tournaments.store');
        Route::get('admin/tournaments/{tournament}', [AdminTournamentController::class, 'show'])->middleware('permission:manage tournaments')->name('api.v1.admin.tournaments.show');
        Route::patch('admin/tournaments/{tournament}', [AdminTournamentController::class, 'update'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.tournaments.update');
        Route::post('admin/tournaments/{tournament}/status', [AdminTournamentController::class, 'status'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.tournaments.status');
        Route::get('admin/tournaments/{tournament}/teams', [AdminTeamController::class, 'index'])->middleware('permission:manage tournaments')->name('api.v1.admin.teams.index');
        Route::post('admin/tournaments/{tournament}/teams', [AdminTeamController::class, 'store'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.teams.store');
        Route::delete('admin/tournaments/{tournament}/teams/{team}', [AdminTeamController::class, 'destroy'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.teams.destroy');
        Route::post('admin/tournaments/{tournament}/teams/{team}/captain', [AdminTeamController::class, 'assignCaptain'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.teams.captain.assign');
        Route::delete('admin/tournaments/{tournament}/teams/{team}/captain', [AdminTeamController::class, 'removeCaptain'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.teams.captain.remove');
        Route::get('admin/tournaments/{tournament}/draft/state', [AdminDraftController::class, 'state'])->middleware('permission:control draft')->name('api.v1.admin.draft.state');
        Route::post('admin/tournaments/{tournament}/draft/start', [AdminDraftController::class, 'start'])->middleware(['permission:control draft', 'throttle:60,1'])->name('api.v1.admin.draft.start');
        Route::post('admin/tournaments/{tournament}/draft/extend', [AdminDraftController::class, 'extend'])->middleware(['permission:control draft', 'throttle:60,1'])->name('api.v1.admin.draft.extend');
        Route::post('admin/tournaments/{tournament}/draft/skip', [AdminDraftController::class, 'skip'])->middleware(['permission:control draft', 'throttle:60,1'])->name('api.v1.admin.draft.skip');
        Route::post('admin/tournaments/{tournament}/draft/pause', [AdminDraftController::class, 'pause'])->middleware(['permission:control draft', 'throttle:60,1'])->name('api.v1.admin.draft.pause');
        Route::post('admin/tournaments/{tournament}/draft/resume', [AdminDraftController::class, 'resume'])->middleware(['permission:control draft', 'throttle:60,1'])->name('api.v1.admin.draft.resume');
        Route::post('admin/tournaments/{tournament}/draft/undo', [AdminDraftController::class, 'undo'])->middleware(['permission:undo latest pick', 'throttle:60,1'])->name('api.v1.admin.draft.undo');
        Route::put('admin/tournaments/{tournament}/draft/setup', [\App\Http\Controllers\Admin\DraftSetupController::class, 'updateApi'])->middleware(['permission:control draft', 'throttle:30,1'])->name('api.v1.admin.draft.setup');
        Route::post('admin/tournaments/{tournament}/draft/select-player', [AdminDraftController::class, 'selectPlayer'])->middleware(['permission:control draft', 'throttle:60,1'])->name('api.v1.admin.draft.select-player');
        Route::post('admin/tournaments/{tournament}/draft/remove-player', [AdminDraftController::class, 'removePlayer'])->middleware(['permission:control draft', 'throttle:60,1'])->name('api.v1.admin.draft.remove-player');
        Route::post('admin/tournaments/{tournament}/draft/reassign-player', [AdminDraftController::class, 'reassignPlayer'])->middleware(['permission:control draft', 'throttle:60,1'])->name('api.v1.admin.draft.reassign-player');
        Route::get('admin/tournaments/{tournament}/players', [AdminPlayerController::class, 'index'])->middleware('permission:manage tournaments')->name('api.v1.admin.players.index');
        Route::post('admin/tournaments/{tournament}/players/manual', [AdminPlayerController::class, 'storeManual'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.players.manual.store');
        Route::post('admin/tournaments/{tournament}/players/{registration}/approve', [AdminPlayerController::class, 'approve'])->middleware(['permission:manage tournaments', 'throttle:60,1'])->name('api.v1.admin.players.approve');
        Route::post('admin/tournaments/{tournament}/players/{registration}/reject', [AdminPlayerController::class, 'reject'])->middleware(['permission:manage tournaments', 'throttle:60,1'])->name('api.v1.admin.players.reject');
        Route::get('admin/tournaments/{tournament}/fixtures', [AdminFixtureController::class, 'index'])->middleware('permission:manage tournaments')->name('api.v1.admin.fixtures.index');
        Route::post('admin/tournaments/{tournament}/fixtures', [AdminFixtureController::class, 'store'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.fixtures.store');
        Route::put('admin/tournaments/{tournament}/fixtures/{fixture}', [AdminFixtureController::class, 'update'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.fixtures.update');
        Route::delete('admin/tournaments/{tournament}/fixtures/{fixture}', [AdminFixtureController::class, 'destroy'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.fixtures.destroy');
        // Stage CRUD
        Route::get('admin/tournaments/{tournament}/stages', [AdminStageController::class, 'index'])->middleware('permission:manage tournaments')->name('api.v1.admin.stages.index');
        Route::post('admin/tournaments/{tournament}/stages', [AdminStageController::class, 'store'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.stages.store');
        Route::get('admin/tournaments/{tournament}/stages/{stage}', [AdminStageController::class, 'show'])->middleware('permission:manage tournaments')->name('api.v1.admin.stages.show');
        Route::patch('admin/tournaments/{tournament}/stages/{stage}', [AdminStageController::class, 'update'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.stages.update');
        Route::delete('admin/tournaments/{tournament}/stages/{stage}', [AdminStageController::class, 'destroy'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.stages.destroy');
        Route::post('admin/tournaments/{tournament}/fixtures/{fixture}/status', [AdminFixtureController::class, 'status'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.fixtures.status');
        Route::post('admin/tournaments/{tournament}/fixtures/{fixture}/create-match', [AdminFixtureController::class, 'createMatch'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.fixtures.create-match');
        Route::get('admin/tournaments/{tournament}/matches', [AdminMatchController::class, 'index'])->middleware('permission:manage tournaments')->name('api.v1.admin.matches.index');
        Route::post('admin/tournaments/{tournament}/matches', [AdminMatchController::class, 'store'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.matches.store');
        Route::get('admin/tournaments/{tournament}/matches/{match}', [AdminMatchController::class, 'show'])->middleware('permission:manage tournaments')->name('api.v1.admin.matches.show');
        Route::patch('admin/tournaments/{tournament}/matches/{match}/overs', [AdminMatchController::class, 'updateOvers'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.matches.overs');
        Route::post('admin/tournaments/{tournament}/matches/{match}/teams/{team}/playing-xi', [AdminMatchController::class, 'playingXi'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.matches.playing-xi');
        Route::post('admin/tournaments/{tournament}/matches/{match}/approve-lineup', [AdminMatchController::class, 'approveLineup'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.matches.approve-lineup');
        Route::post('admin/tournaments/{tournament}/matches/{match}/toss', [AdminMatchController::class, 'toss'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.matches.toss');
        Route::post('admin/matches/{match}/result/submit', [AdminResultController::class, 'submit'])->middleware(['permission:control draft', 'throttle:30,1'])->name('api.v1.admin.matches.result.submit');
        Route::post('admin/matches/{match}/result/approve', [AdminResultController::class, 'approve'])->middleware(['permission:manage tournaments', 'throttle:30,1'])->name('api.v1.admin.matches.result.approve');
        Route::get('super-admin/dashboard', [SuperAdminController::class, 'dashboard'])->middleware(['permission:manage system'])->name('api.v1.super-admin.dashboard');
        Route::get('super-admin/api-clients', [SuperAdminController::class, 'clients'])->middleware(['permission:manage api clients'])->name('api.v1.super-admin.api-clients.index');
        Route::post('super-admin/api-clients', [SuperAdminController::class, 'createClient'])->middleware(['permission:manage api clients', 'throttle:30,1'])->name('api.v1.super-admin.api-clients.store');
        Route::post('super-admin/api-clients/{apiClient}/toggle', [SuperAdminController::class, 'toggleClient'])->middleware(['permission:manage api clients', 'throttle:60,1'])->name('api.v1.super-admin.api-clients.toggle');
        Route::get('super-admin/api-sessions', [SuperAdminController::class, 'sessions'])->middleware(['permission:manage api clients'])->name('api.v1.super-admin.api-sessions.index');
        Route::post('super-admin/api-sessions/{token}/revoke', [SuperAdminController::class, 'revokeSession'])->middleware(['permission:revoke api tokens', 'throttle:60,1'])->name('api.v1.super-admin.api-sessions.revoke');
        Route::get('super-admin/audit-logs', [SuperAdminController::class, 'auditLogs'])->middleware(['permission:view all audit logs'])->name('api.v1.super-admin.audit-logs');
        Route::get('super-admin/health', [SuperAdminController::class, 'health'])->middleware(['permission:view system health'])->name('api.v1.super-admin.health');
        Route::get('super-admin/users', [SuperAdminController::class, 'users'])->middleware(['permission:manage system'])->name('api.v1.super-admin.users.index');
        Route::get('super-admin/users/{user}', [SuperAdminController::class, 'user'])->middleware(['permission:manage system'])->name('api.v1.super-admin.users.show');
        Route::post('super-admin/users/{user}/role', [SuperAdminController::class, 'updateUserRole'])->middleware(['permission:manage system', 'throttle:30,1'])->name('api.v1.super-admin.users.role');
        Route::post('super-admin/users/{user}/revoke-sessions', [SuperAdminController::class, 'revokeUserSessions'])->middleware(['permission:manage system', 'throttle:30,1'])->name('api.v1.super-admin.users.revoke-sessions');
        Route::get('super-admin/tournaments', [SuperAdminController::class, 'tournaments'])->middleware(['permission:manage system'])->name('api.v1.super-admin.tournaments.index');
        Route::get('super-admin/tournaments/{tournament}', [SuperAdminController::class, 'tournament'])->middleware(['permission:manage system'])->name('api.v1.super-admin.tournaments.show');
    });
});
