<?php if (isset($component)) { $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54 = $attributes; } ?>
<?php $component = App\View\Components\AppLayout::resolve([] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('app-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\AppLayout::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
     <?php $__env->slot('header', null, []); ?> <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3"><div><p class="cricket-kicker mb-2">Platform operations</p><h1 class="display-6 fw-bold mb-2">All Matches</h1><p class="text-secondary mb-0">Monitor all matches across the platform.</p></div><a href="<?php echo e(route('super-admin.dashboard')); ?>" class="btn btn-light"><i class="fa-solid fa-arrow-left me-2"></i>Control plane</a></div> <?php $__env->endSlot(); ?>
    <div class="container pb-5">
        <div class="row g-2 mb-4"><?php $__currentLoopData = ['scheduled' => 'Scheduled', 'toss_pending' => 'Toss Pending', 'live' => 'Live', 'completed' => 'Completed', 'abandoned' => 'Abandoned', 'cancelled' => 'Cancelled']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-6 col-md-4 col-xl-2"><a href="<?php echo e(route('super-admin.matches.index', ['status' => $status])); ?>" class="cricket-surface p-3 h-100 text-decoration-none d-block"><div class="small text-secondary"><?php echo e($label); ?></div><div class="h3 fw-bold text-dark mb-0"><?php echo e($statusCounts[$status] ?? 0); ?></div></a></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
        <div class="cricket-surface p-4 mb-4"><form method="GET" class="row g-2 align-items-end"><div class="col-lg-10"><label class="form-label small text-secondary">Lifecycle status</label><select name="status" class="form-select"><option value="">All statuses</option><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status); ?>" <?php if($selectedStatus === $status): echo 'selected'; endif; ?>><?php echo e(ucfirst($status)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-lg-2 d-flex gap-2"><button class="btn btn-success flex-grow-1">Filter</button><a href="<?php echo e(route('super-admin.matches.index')); ?>" class="btn btn-light">Reset</a></div></form></div>
        <div class="cricket-surface overflow-hidden"><div class="d-flex justify-content-between align-items-center gap-3 p-4 border-bottom"><div><p class="cricket-kicker mb-1">Match directory</p><h2 class="h4 fw-bold mb-0">All Matches</h2></div><span class="small text-secondary"><?php echo e($matches->total()); ?> total matches</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>ID</th><th>Tournament/Type</th><th>Teams</th><th>Status</th><th>Overs</th><th class="text-end">Action</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $matches; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $match): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td>#<?php echo e($match->id); ?></td><td><?php if($match->tournament): ?><div class="fw-semibold"><?php echo e($match->tournament->name); ?></div><?php else: ?><span class="badge text-bg-secondary">Custom Match</span><?php endif; ?></td><td><div class="fw-semibold"><?php echo e($match->fixture->homeTeam->name ?? 'TBD'); ?> vs <?php echo e($match->fixture->awayTeam->name ?? 'TBD'); ?></div></td><td><span class="badge <?php echo e($match->status === 'live' ? 'text-bg-success' : ($match->status === 'completed' ? 'text-bg-dark' : 'text-bg-light')); ?>"><?php echo e(ucfirst($match->status)); ?></span></td><td><?php echo e($match->overs_per_innings); ?></td><td class="text-end"><a href="<?php echo e(route('super-admin.matches.show', $match)); ?>" class="btn btn-sm btn-outline-success">Match Center</a></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="text-center py-5 text-secondary">No matches found.</td></tr><?php endif; ?></tbody></table></div></div><div class="mt-3"><?php echo e($matches->links()); ?></div>
    </div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $attributes = $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $component = $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/super-admin/matches/index.blade.php ENDPATH**/ ?>