<?php if (isset($component)) { $__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.public-layout','data' => ['title' => 'Cricket Draft OS · Tournament operations, in one place']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('public-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['title' => 'Cricket Draft OS · Tournament operations, in one place']); ?>
    <?php
        $workspace = route('login');
        if (auth()->check()) {
            $user = auth()->user();
            $workspace = match (true) {
                $user->hasRole('super_admin') => route('super-admin.dashboard'),
                $user->hasRole('admin') => route('admin.dashboard'),
                $user->hasRole('captain') => route('captain.dashboard'),
                $user->hasRole('player') => route('player.tournaments.index'),
                default => route('dashboard'),
            };
        }
        $featuredTournament = $featured['tournament'] ?? null;
        $featuredState = $featured['state'] ?? null;
        $featuredSummary = $featuredState['summary'] ?? null;
        $featuredProgress = ($featuredSummary && $featuredSummary['total'] > 0)
            ? round(($featuredSummary['selected'] / $featuredSummary['total']) * 100)
            : 0;
    ?>

    <section class="saas-hero cricket-hero text-white">
        <div class="container position-relative py-5 py-lg-6">
            <div class="row align-items-center g-5 py-lg-5">
                <div class="col-lg-7">
                    <div class="d-inline-flex align-items-center gap-2 saas-eyebrow saas-eyebrow-dark mb-4"><span class="cricket-live-dot"></span><span>Cricket operations, without the spreadsheet chaos</span></div>
                    <h1 class="saas-hero-title mb-4">Run every tournament from <span class="text-lime">first pick</span> to final over.</h1>
                    <p class="saas-hero-copy mb-4">Cricket Draft OS brings draft rooms, fixtures, live scoring, standings, reports, and mobile-ready data into one authoritative workspace for your entire tournament team.</p>
                    <div class="d-flex flex-column flex-sm-row gap-3">
                        <?php if($featuredTournament && $featuredTournament->status === 'live'): ?>
                            <a class="btn btn-lime btn-lg" href="<?php echo e(route('public.live.center')); ?>"><i class="fa-solid fa-tower-broadcast me-2"></i>Watch live draft</a>
                        <?php elseif(auth()->check()): ?>
                            <a class="btn btn-lime btn-lg" href="<?php echo e($workspace); ?>"><i class="fa-solid fa-arrow-right me-2"></i>Open workspace</a>
                        <?php else: ?>
                            <a class="btn btn-lime btn-lg" href="<?php echo e(route('register')); ?>">Create player account <i class="fa-solid fa-arrow-right ms-2"></i></a>
                        <?php endif; ?>
                        <a class="btn btn-outline-light btn-lg" href="<?php echo e(route('public.how-it-works')); ?>">See how it works <i class="fa-solid fa-play ms-2"></i></a>
                    </div>
                    <div class="d-flex flex-wrap gap-4 mt-5 small text-white-50"><span><i class="fa-solid fa-circle-check me-2 text-lime"></i>Server-authoritative state</span><span><i class="fa-solid fa-circle-check me-2 text-lime"></i>Live from web to mobile</span><span><i class="fa-solid fa-circle-check me-2 text-lime"></i>No placeholder results</span></div>
                </div>
                <div class="col-lg-5">
                    <div class="saas-command-card">
                        <div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><div class="small text-white-50 text-uppercase fw-bold" style="letter-spacing:.13em;">Live command center</div><div class="h4 fw-bold mb-0 mt-1"><?php echo e($featuredTournament?->name ?: 'Your tournament, visualized'); ?></div></div><span class="badge bg-lime text-dark"><?php echo e($featuredTournament ? ucfirst($featuredTournament->status) : 'Ready'); ?></span></div>
                        <?php if($featuredTournament): ?>
                            <div class="d-flex align-items-center gap-3 mb-4"><?php if($featuredTournament->logo_path): ?><img src="<?php echo e(\Illuminate\Support\Facades\Storage::disk('public')->url($featuredTournament->logo_path)); ?>" alt="<?php echo e($featuredTournament->name); ?> logo" class="saas-avatar"><?php else: ?><span class="saas-avatar saas-avatar-icon"><i class="fa-solid fa-trophy"></i></span><?php endif; ?><div><div class="fw-bold"><?php echo e($featuredTournament->name); ?></div><div class="small text-white-50"><?php echo e($featuredTournament->season_name ?: 'Tournament season'); ?> · <?php echo e($featured['teams_count']); ?> teams</div></div></div>
                            <?php if($featuredState): ?>
                                <div class="saas-command-screen"><div class="d-flex justify-content-between small text-white-50 mb-2"><span><?php echo e($featuredState['current_team']['name'] ?? 'Waiting for team'); ?></span><span><?php echo e($featuredSummary['selected']); ?>/<?php echo e($featuredSummary['total']); ?> selected</span></div><div class="saas-timer"><?php echo e($featuredState['timer']['remaining_seconds'] === null ? '--:--' : gmdate('i:s', max(0, $featuredState['timer']['remaining_seconds']))); ?></div><div class="progress mt-3" style="height:.42rem;background:rgba(255,255,255,.16);"><div class="progress-bar bg-lime" style="width:<?php echo e($featuredProgress); ?>%;"></div></div><div class="d-flex justify-content-between mt-3 small text-white-50"><span>Pick <?php echo e($featuredState['current_pick_number'] ?? '—'); ?></span><span>Revision <?php echo e($featuredState['revision']); ?></span></div></div>
                            <?php else: ?>
                                <div class="saas-command-screen"><div class="small text-white-50">Tournament details</div><div class="h5 fw-bold mb-0 mt-2">Registration and setup stay in one controlled workflow.</div></div>
                            <?php endif; ?>
                        <?php else: ?>
                            <div class="saas-command-screen text-center py-5"><i class="fa-solid fa-layer-group fs-1 text-lime mb-3"></i><div class="h5 fw-bold">Waiting for the first tournament</div><div class="small text-white-50">Live metrics will appear as soon as an event is opened.</div></div>
                        <?php endif; ?>
                        <div class="d-flex justify-content-between align-items-center mt-4 small text-white-50"><span><i class="fa-solid fa-shield-halved me-2 text-lime"></i>Authoritative data</span><span><?php echo e($homepageStats['total']); ?> public events</span></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="container saas-proof-row py-4 py-lg-5"><div class="row g-3"><div class="col-6 col-lg-3"><div class="saas-proof-item"><div class="saas-proof-value"><?php echo e($homepageStats['total']); ?></div><div class="small text-secondary">Public tournaments</div></div></div><div class="col-6 col-lg-3"><div class="saas-proof-item"><div class="saas-proof-value text-success"><?php echo e($homepageStats['live']); ?></div><div class="small text-secondary">Live right now</div></div></div><div class="col-6 col-lg-3"><div class="saas-proof-item"><div class="saas-proof-value"><?php echo e($homepageStats['registration']); ?></div><div class="small text-secondary">Open registration</div></div></div><div class="col-6 col-lg-3"><div class="saas-proof-item"><div class="saas-proof-value"><?php echo e($homepageStats['teams']); ?></div><div class="small text-secondary">Active teams</div></div></div></div></section>

    <section class="container saas-section py-5" id="platform"><div class="row align-items-end g-4 mb-5"><div class="col-lg-7"><p class="cricket-kicker mb-2">One operating layer</p><h2 class="saas-section-title mb-3">A serious tournament platform for every role.</h2><p class="lead text-secondary mb-0">Admins control the system, captains make the calls, scorers record the game, and fans follow the same live truth.</p></div><div class="col-lg-5 text-lg-end"><a href="<?php echo e(route('public.features')); ?>" class="btn btn-outline-success">Explore all capabilities <i class="fa-solid fa-arrow-right ms-2"></i></a></div></div><div class="row g-4"><div class="col-md-6 col-xl-3"><div class="saas-feature-card h-100"><div class="saas-feature-icon"><i class="fa-solid fa-shuffle"></i></div><h3 class="h5 fw-bold">Draft orchestration</h3><p class="small text-secondary mb-0">Round gates, assigned picks, captain-only selection, timer controls, undo, skip, and audit-ready history.</p></div></div><div class="col-md-6 col-xl-3"><div class="saas-feature-card h-100"><div class="saas-feature-icon"><i class="fa-solid fa-calendar-days"></i></div><h3 class="h5 fw-bold">Fixtures and formats</h3><p class="small text-secondary mb-0">Schedule matches, set venues, configure overs, approve lineups, and move from fixture to match.</p></div></div><div class="col-md-6 col-xl-3"><div class="saas-feature-card h-100"><div class="saas-feature-icon"><i class="fa-solid fa-chart-line"></i></div><h3 class="h5 fw-bold">Live cricket scoring</h3><p class="small text-secondary mb-0">Ball-by-ball deliveries, wickets, extras, innings state, scorecards, points, and net run rate.</p></div></div><div class="col-md-6 col-xl-3"><div class="saas-feature-card h-100"><div class="saas-feature-icon"><i class="fa-solid fa-mobile-screen-button"></i></div><h3 class="h5 fw-bold">Web and mobile ready</h3><p class="small text-secondary mb-0">A versioned API keeps public, captain, scorer, admin, and mobile workflows on the same backend.</p></div></div></div></section>

    <section class="container saas-section py-5" id="registration"><div class="d-flex flex-column flex-md-row align-items-md-end justify-content-between gap-3 mb-5"><div><p class="cricket-kicker mb-2">Registration</p><h2 class="saas-section-title mb-3">Find an open tournament.</h2><p class="text-secondary mb-0">Apply through the player workspace when registration is open.</p></div><a href="<?php echo e(route('public.tournaments.index')); ?>" class="btn btn-outline-success">View all tournaments <i class="fa-solid fa-arrow-right ms-2"></i></a></div><?php if($registrationTournaments->isEmpty()): ?><div class="saas-empty-state"><span class="saas-avatar"><i class="fa-solid fa-calendar-check"></i></span><div><h3 class="h5 fw-bold">No registration window is open</h3><p class="text-secondary mb-0">Check back when an administrator moves a tournament into registration.</p></div></div><?php else: ?><div class="row g-4"><?php $__currentLoopData = $registrationTournaments->take(3); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php $tournament = $item['tournament']; ?><div class="col-md-6 col-xl-4"><div class="saas-directory-card h-100 d-flex flex-column"><div class="d-flex justify-content-between align-items-start mb-4"><span class="saas-avatar"><i class="fa-solid fa-user-plus"></i></span><span class="badge text-bg-light"><?php echo e(ucfirst($tournament->status)); ?></span></div><h3 class="h5 fw-bold mb-1"><?php echo e($tournament->name); ?></h3><div class="small text-success fw-bold mb-2"><?php echo e($tournament->season_name ?: 'Tournament season'); ?></div><p class="small text-secondary mb-4"><?php echo e($tournament->venue ?: $tournament->location ?: 'Location to be announced'); ?><?php echo e($tournament->city ? ', '.$tournament->city : ''); ?></p><a href="<?php echo e(auth()->check() && auth()->user()->hasRole('player') ? route('player.tournaments.index') : route('register')); ?>" class="btn btn-success w-100 mt-auto">Register interest <i class="fa-solid fa-arrow-right ms-2"></i></a></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endif; ?></section>

    <section class="saas-dark-section py-5" id="match-coverage"><div class="container py-lg-4"><div class="row align-items-center g-5"><div class="col-lg-6"><p class="cricket-kicker text-lime mb-2">Live activity</p><h2 class="saas-section-title text-white mb-3">Real tournaments on the board.</h2><p class="text-white-50 mb-4">These cards are populated directly from the current database state. When an admin starts a draft, everyone sees the same live board and timer.</p><a href="<?php echo e(route('public.live.center')); ?>" class="btn btn-lime">Open live draft center <i class="fa-solid fa-arrow-right ms-2"></i></a></div><div class="col-lg-6"><div class="row g-3"><?php $__empty_1 = true; $__currentLoopData = $liveTournaments->take(2); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?> <?php $tournament = $item['tournament']; $state = $item['state']; $summary = $state['summary']; $progress = $summary['total'] > 0 ? round(($summary['selected'] / $summary['total']) * 100) : 0; ?><div class="col-md-6"><div class="saas-live-card h-100"><div class="d-flex justify-content-between align-items-start mb-4"><span class="saas-avatar saas-avatar-sm"><i class="fa-solid fa-tower-broadcast"></i></span><span class="badge bg-lime text-dark">Live</span></div><h3 class="h5 text-white fw-bold mb-1"><?php echo e($tournament->name); ?></h3><div class="small text-white-50 mb-4"><?php echo e($item['teams_count']); ?> teams · <?php echo e($tournament->season_name ?: 'Current season'); ?></div><div class="small text-white-50 d-flex justify-content-between"><span>On the clock</span><strong class="text-white"><?php echo e($state['current_team']['name'] ?? 'Waiting'); ?></strong></div><div class="progress mt-3" style="height:.35rem;background:rgba(255,255,255,.12);"><div class="progress-bar bg-lime" style="width:<?php echo e($progress); ?>%;"></div></div><a href="<?php echo e(route('public.draft.show', $tournament)); ?>" class="btn btn-sm btn-outline-light w-100 mt-4">Open live board</a></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="col-12"><div class="saas-empty-dark"><span class="saas-avatar"><i class="fa-solid fa-tower-broadcast"></i></span><div><h3 class="h5 text-white fw-bold">No tournament is live right now</h3><p class="text-white-50 mb-0">When an admin starts a draft, its live board will appear here automatically.</p></div></div></div><?php endif; ?></div></div></div></div></section>

    <section class="container saas-section py-5"><div class="row align-items-center g-5"><div class="col-lg-5"><p class="cricket-kicker mb-2">From setup to scorecard</p><h2 class="saas-section-title mb-3">Make every match feel organised before the first ball.</h2><p class="text-secondary mb-4">Replace disconnected tools with a clear operational flow that keeps decisions, records, and public updates together.</p><a href="<?php echo e(route('public.how-it-works')); ?>" class="btn btn-success">See the operating flow <i class="fa-solid fa-arrow-right ms-2"></i></a></div><div class="col-lg-7"><div class="saas-timeline"><div class="saas-timeline-step"><span>01</span><div><h3 class="h6 fw-bold">Configure the tournament</h3><p class="small text-secondary mb-0">Set the season, teams, registration, squad size, draft rounds, and default overs.</p></div></div><div class="saas-timeline-step"><span>02</span><div><h3 class="h6 fw-bold">Run the draft room</h3><p class="small text-secondary mb-0">Start each pick manually, control the clock, and keep captain decisions auditable.</p></div></div><div class="saas-timeline-step"><span>03</span><div><h3 class="h6 fw-bold">Schedule and score</h3><p class="small text-secondary mb-0">Turn approved squads into fixtures and capture every delivery inside the scorer room.</p></div></div><div class="saas-timeline-step"><span>04</span><div><h3 class="h6 fw-bold">Publish the truth</h3><p class="small text-secondary mb-0">Public scorecards, standings, reports, and mobile clients stay in sync automatically.</p></div></div></div></div></div></section>

    <section class="container pb-5"><div class="saas-cta"><div><p class="cricket-kicker mb-2">Ready when your tournament is</p><h2 class="h2 fw-bold mb-2">Bring the whole competition into one workspace.</h2><p class="text-secondary mb-0">Browse public tournaments, follow live boards, or sign in to operate your role.</p></div><div class="d-flex flex-column flex-sm-row gap-2"><?php if(auth()->check()): ?><a href="<?php echo e($workspace); ?>" class="btn btn-success">Open workspace <i class="fa-solid fa-arrow-right ms-2"></i></a><?php else: ?><a href="<?php echo e(route('register')); ?>" class="btn btn-success">Create account <i class="fa-solid fa-arrow-right ms-2"></i></a><?php endif; ?><a href="<?php echo e(route('public.tournaments.index')); ?>" class="btn btn-outline-success">Browse tournaments</a></div></div></section>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b)): ?>
<?php $attributes = $__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b; ?>
<?php unset($__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b)): ?>
<?php $component = $__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b; ?>
<?php unset($__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b); ?>
<?php endif; ?>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/welcome.blade.php ENDPATH**/ ?>